package com.treecio.crowdio.network.fcm

import com.google.firebase.iid.FirebaseInstanceId
import com.google.firebase.iid.FirebaseInstanceIdService
import timber.log.Timber


/**
 * Service for obtaining the registration token generated by the FCM SDK.
 */
class FirebaseInstanceIdService : FirebaseInstanceIdService() {

    override fun onTokenRefresh() {
        // Get updated InstanceID token.
        val token = FirebaseInstanceId.getInstance().token

        //NetworkPreferences(this).firebaseIIDToken = token
        Timber.d("Firebase token: " + token)
    }

}
